version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_inventory
      - DB_USER=postgres
      - DB_PASS=123
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "npx sequelize-cli db:migrate && npm start"

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=db_inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local